### PR TITLE
[GHO-57] Force the admin interface to be in English

### PR DESCRIPTION
**Pull request by orakili**
Ticket: GHO-57

This PR ensures the admin interface is always in English to ensure a consistent editorial experience:

Screen Shot 2020-11-04 at 16 13 37
Screen Shot 2020-11-04 at 16 12 04

## Testing

@rupl  Normally just `drush cim` and `drush cr` but let me know if you have an issue like that:

Screen Shot 2020-11-04 at 17 46 34

### CODE REVIEW

**Comment by rupl** [comment]
I got a totally different error. yay!

```
 [notice] Synchronized configuration: update language.types.
 [notice] Synchronized configuration: update core.entity_form_display.taxonomy_term.section.default.
 [notice] Finalizing configuration synchronization.
 [error]  Drupal\Core\Config\ConfigException: Errors occurred during import in Drush\Drupal\Commands\config\ConfigImportCommands->doImport() (line 343 of /srv/www/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php).

In ConfigImportCommands.php line 357:

  The import failed due to the following reasons:
  Unexpected error during import with operation update for core.entity_form_display.taxonomy_term.sect
  ion.default: The &quot;gho-general-language-admin&quot; plugin does not exist. Valid plugin IDs for
  Drupal\language\LanguageNegotiationMethodManager are: language-browser, language-content-entity, lan
  guage-selected, language-session, language-interface, language-url, language-url-fallback, language-
  user, language-user-admin
```

**Comment by rupl** [comment]
Ok despite the config error it did report finishing, and after a cache clear I am seeing LTR admin pages even when the URL contains `/ar/`

image

**Review by rupl — APPROVED** [review]
Once Travis agrees, I consider this done. My functional test was trouble-free.

**Review by rupl — APPROVED** [review]
Sorry I thought there was a problem, but I started from a fresh DB and tested the whole process again and it is indeed working fine.

**Comment by orakili** [comment]
Tested the same content of the PR but with the `config/language.types.yml` reverted to the main branch's one and travis is happy so there is something it doesn't like with the changes there....

**Comment by rupl** [comment]
Honestly this would be nice to have, but it's not critical. Anyone who is tasked with entering arabic content would presumably be able to read that language, and won't find it as difficult to decipher as we would.

**Comment by orakili** [comment]
@rupl, finally found and fixed the issue. Could you check that it's still working as advertised? Thanks.

**Review by rupl — APPROVED** [review]
Third post-travis-fix review still working smoothly. Huzzah!

**Comment by rupl** [comment]
No more errors during config sync or cache rebuild. Admin UI completely intact (always LTR) and the menu bar is untranslated but RTL when viewing publicly-themed pages. 👍

**Pull request merged**
