### PR TITLE
[GHO-99] Menus

### PR DESCRIPTION
**Pull request by orakili**
Ticket: GHO-99, GHO-85

Allow editors to modify menus  via structure > menus and enable menu translations.

`drush cim`, `drush cr`, log in as normal admin user, go to "structure > menus", click on edit menu for "main menu", check you can re-order, rename and translate sub-menus.

### CODE REVIEW

**Review by rupl — COMMENTED** [review]
Reordering menu items was no problem, but translating a menu item I got this error:

```
Error:
Non-translatable fields can only be changed when updating the original language.
```

The form is quite short and even before saving displays a warning:

```
Warning:
Fields that apply to all languages are hidden to avoid conflicting changes.
```

I looked through permissions and did see one that might be related: "Translate custom menu link" but enabling did not change behavior, and actually testing with user/1 produces the same error.

**Comment by rupl** [comment]
The other field on the Translate form is **Parent link** which I imagine wouldn't need to be translated. Is there some way of choosing what gets translated and what gets omitted from this form?

**Comment by rupl** [comment]
The menu item translation is successful as user/1 — reviewing perms one more time to see if something sticks out

**Comment by rupl** [comment]
Ok a more detailed report of what I've seen as I posted all the short comments above:

When I click **Edit Menu** and then go to Translate an individual menu link, **I am successful for top-level links only** for both user/1 and the `administrator` role. I was able to translate _Introduction_ into all four languages: two translations made by a user with `administrator` role, and one by user/1.

When I try to Translate a second-level menu link, both user/1 and `administrator` display the error I initially noted above:

> Non-translatable fields can only be changed when updating the original language.

**Comment by orakili** [comment]
@rupl The issue was with a setting in https://gho.test/admin/config/regional/content-language to hide the non-translatable fields on the form. Apparently Drupal doesn't like itself...

**Comment by rupl** [comment]
Good to know about the settings! Yeah I was looking for more of a "Manage form display" type tab but obviously it's not there.

**Comment by rupl** [comment]
Yes now there are many more form items on the translation page and second-level menu items are translating as expected.

**Review by rupl — APPROVED** [review]

**Pull request merged**
