### PR TITLE
CD-270 update base theme

### PR DESCRIPTION
**Pull request by left23**
This PR add the v3.0.1 base theme and makes the necessary tweaks to the subtheme to accommodate.

Run `composer install`

**The main changes are:**

1. Full width header and footer and removal of side margins means the width of the container increases slightly.
2. The body background is now white, no longer light grey.
3. The header height increases due to 6px bottom border, and the header grid, the placement of the mobile menu dropdown and the active menu item bottom border change to accommodate.
4. Sticky footer for anon users
5. Remove classy as base theme https://github.com/UN-OCHA/common_design/commit/378e343b8fbe9192657801ef2f0492374e7d1412
6. Folders have been added to organise templates https://github.com/UN-OCHA/common_design/tree/main/templates. If a template is missing it may have been moved, or it may have come from Classy base theme.
7. Rename and remove variables and introduce CSS custom properties https://github.com/UN-OCHA/common_design/blob/main/sass/cd/_cd-variables.scss and update subtheme accordingly.
8. Update node version and replace gulp-sass - run `nvm use` and `npm i` to update
9. Remove page title related preprocess functions from the subtheme, in favour of base theme. There is config for the base theme settings - run `drush cim`

I am writing release notes for v3.0.0 which I will share asap.

I would like to deploy this asap so I can run VRTs on the server. I have run them locally and due to the nature of the changes, they will typically fail. VRT results I can share will allow me point out acceptable visual differences.

URLs for testing https://docs.google.com/spreadsheets/d/1GcqvK2PWuSZbLKEvQQNKtBc0xOx-GzTSbiIdd6HP5lI/edit#gid=1791254445

### CODE REVIEW

**Comment by left23** [comment]
@rupl @orakili Can you advise me on the Build failure?
```
There was 1 error:

1) Drupal\Tests\gho_general\ExistingSite\HomePageTest::testHomePage

Behat\Mink\Exception\ResponseTextException: The text "Global Humanitarian Overview" was not found anywhere in the text of the current page.
```

What is the current page in this scenario?

**Comment by rupl** [comment]
@left23 I found the test at https://github.com/UN-OCHA/gho-site/blob/3f9b102682430571f39fe122786d2814085f387c/html/modules/custom/gho_general/tests/src/ExistingSite/HomePageTest.php#L17-L22

It's testing `<front>` and when I viewed source of my local environment I found 11 instances (case-insensitive). Some are content (e.g. the alt for the huge SVG above the fold, the meta tags), but others are hardcoded in the menu, such as the logo of the navigation bar.

I honestly had forgotten we had this test and it has not failed often (or ever?) that I know of. I looked at the Travis log and nothing broke before running the test. I briefly looked at running tests locally but the travis file includes many steps and I couldn't get it working with a few minutes of fiddling.

Perhaps we can wait for Jonathan and he'll either have a quick answer, or at least a better idea of how to go about debugging this. Sorry I can't be of more help!

**Comment by rupl** [comment]
hey nice, the test is fixed!

**Comment by left23** [comment]
I'm currently investigating why IE11 breaks so badly - either the css-pony-fill isn't loading or the CSS variables as SASS values isn't working well with the ponyfill...

**Comment by left23** [comment]
I renamed the branch and needed to open a new PR https://github.com/UN-OCHA/gho-site/pull/224

**Pull request closed without merging**
